name: 🌟 Feature Request
description: Suggest a new feature or improvement
title: "[X][project] short description"
type: Feature

body:
  - type: textarea
    id: summary
    attributes:
      label: What do you want to add or change?
      description: Briefly describe the new feature or improvement you have in mind.
      placeholder: I want users to be able to ...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Explain why this feature is valuable and how it improves the product.
      placeholder: It reduces clutter and helps users focus on ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define the minimum requirements for this feature to be considered complete.
      placeholder: |
        - Users should be able to ...
        - UI shows proper result on the ...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story (Optional)
      description: Write the feature request in user story format.
      placeholder: |
        As a manager, I want to ..., so that I can ...

  - type: textarea
    id: solution
    attributes:
      label: Any implementation ideas?
      description: Share any thoughts on how this could be implemented technically or visually.
      placeholder: Maybe extend the existing ... and update the ...

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Include mockups, references, or any other useful context.
      placeholder: Add links, screenshots, mockups, or related resources here.
